# 05/2024 created
name: Update Plugin

on: [push]

jobs:
    update-demoshops:
        container: alpine:3.14
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: apk add --no-cache jq curl

            - name: Get Composer Name
              run: |
                  COMPOSER_NAME=$(jq -r .name composer.json)
                  echo "COMPOSER_NAME=$COMPOSER_NAME" >> $GITHUB_ENV

            - name: Build urls.txt
              run: |
                  cat << EOF > urls.txt
                  url = "${{ secrets.UPDATE_URL_SW64 }}/${{ env.COMPOSER_NAME }}"
                  url = "${{ secrets.UPDATE_URL_SW65 }}/${{ env.COMPOSER_NAME }}"
                  url = "${{ secrets.UPDATE_URL_SW66 }}/${{ env.COMPOSER_NAME }}"
                  EOF

            - name: Trigger Plugin Update on demoshops
              run: |
                  curl -f -sS -X GET --parallel --parallel-immediate --parallel-max 8 --config urls.txt

