# 05/2024 created
name: Update Plugin

on: [push]

jobs:
    update-sw64:
        container: alpine:3.14
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: apk add --no-cache jq curl

            - name: Get Composer Name
              run: |
                  COMPOSER_NAME=$(jq -r .name composer.json)
                  echo "COMPOSER_NAME=$COMPOSER_NAME" >> $GITHUB_ENV

            - name: Trigger Update Plugin on sw64 demoshop
              run: |
                  curl -f -sS -X GET "${{ secrets.UPDATE_URL_SW64 }}/${{ env.COMPOSER_NAME }}"

    update-sw65:
        container: alpine:3.14
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: apk add --no-cache jq curl

            - name: Get Composer Name
              run: |
                  COMPOSER_NAME=$(jq -r .name composer.json)
                  echo "COMPOSER_NAME=$COMPOSER_NAME" >> $GITHUB_ENV

            - name: Trigger Update Plugin on sw65 demoshop
              run: |
                  curl -f -sS -X GET "${{ secrets.UPDATE_URL_SW65 }}/${{ env.COMPOSER_NAME }}""

    update-sw66:
        container: alpine:3.14
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: apk add --no-cache jq curl

            - name: Get Composer Name
              run: |
                  COMPOSER_NAME=$(jq -r .name composer.json)
                  echo "COMPOSER_NAME=$COMPOSER_NAME" >> $GITHUB_ENV

            - name: Trigger Update Plugin on sw66 demoshop
              run: |
                  curl -f -sS -X GET "${{ secrets.UPDATE_URL_SW66 }}/${{ env.COMPOSER_NAME }}""

